### ISSUE TITLE
about gpu

### ISSUE THREAD

**Issue by iaOlivia** [z-fabian/MRAugment#2]
Hi,
Thanks for your contribution!
can you please tell me which gpu you used?

**Comment by z-fabian** [comment]
Hi,

We trained the models on 4x (single-coil) / 8x (multi-coil) Quadro RTX 5000 GPUs.

**Comment by iaOlivia** [comment]
So it seems diffucult train with 2x RTX 4090?

**Comment by z-fabian** [comment]
Any GPU should work as long as it has CUDA support and at least 16GB RAM. It may take a long time to train on larger datasets with 2x GPUs however.

**Comment by iaOlivia** [comment]
Thank you for guidance.
